vizhinjam/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('vizhinjamport.urls'))
    
]

vizhinjamport/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.landing, name='landing'),
    path('regs', views.reg, name='reg'),
    path('register_user',views.register_user,name='register_user'),
    path('register_company',views.register_company,name='register_company'),
    path('register_contractor',views.register_contractor,name='register_contractor'),
    path('user_list',views.user_list,name='user_list'),
    path('company_list',views.company_list,name='company_list'),
    path('contractor_list',views.contractor_list,name='contractor_list'),
    path('userlogin',views.login,name='userlogin'),
    path('userhome',views.userhome,name='userhome'),
    path('companyhome',views.companyhome,name='companyhome'),
    path('contractorhome',views.contractorhome,name='contractorhome'),
    path('register_ship',views.register_ship,name='register_ship'),
    path('ship_list',views.ship_list,name='ship_list'),
    path('edit_ship/<int:id>/',views.edit_ship,name='edit_ship'),
    path('delete_ship/<int:id>/',views.delete_ship,name='delete_ship'),
    path('ship_user',views.search_ship,name='ship_user'),
    path('edit_user',views.edit_user,name='edit_user'),
    path('edit_company',views.edit_company,name='edit_company'),
    path('edit_contractor',views.edit_contractor,name='edit_contractor'),
    path('export/<int:id>/',views.export,name='export'),
    path('export_list',views.export_list,name='export_list'),
    path('edit_export/<int:id>/',views.edit_export,name='edit_export'),
    path('cancel_export/<int:id>/',views.cancel_export,name='cancel_export'),
    path('export_comp_list',views.export_comp_list,name='export_comp_list'),
    
    path('refund_export/<int:id>/',views.refund_export,name='refund_export'),
    path('addnews',views.addnews,name='addnews'),
    path('admin_news_list',views.admin_news_list,name='admin_news_list'),
    path('edit_news/<int:id>/',views.edit_news,name='edit_news'),
    path('delete_news/<int:id>/',views.delete_news,name='delete_news'),
    path('news_list',views.news_list,name='news_list'),
    path('user_news_list',views.user_news_list,name='user_news_list'),
    path('company_news_list',views.company_news_list,name='company_news_list'),
    path('contractor_news_list',views.contractor_news_list,name='contractor_news_list'),

    path('Ship_track/<int:id>/',views.ship_track,name='ship_track'),
    path('Ship_track_list/<int:id>/',views.ship_track_list,name='ship_track_list'),
    path('edit_ship_track/<int:id>/<int:sid>/',views.edit_ship_track,name='edit_ship_track'),
    path('delete_ship_track/<int:id>/<int:sid>/',views.delete_ship_track,name='delete_ship_track'),
    path('user_track_ship/<int:id>/',views.user_track_ship,name='user_track_ship'),


    path('admin_header',views.admin_header,name='admin_header'),
    path('company_approve/<int:id>/',views.company_approve,name='company_approve'),
    path('company_reject/<int:id>/',views.company_reject,name='company_reject'),
    path('contractor_approve/<int:id>/',views.contractor_approve,name='contractor_approve'),
    path('contractor_reject/<int:id>/',views.contractor_reject,name='contractor_reject'),
    
    path('exportcharges',views.exportcharges,name='exportcharges'),
    path('exportcharges_list',views.exportcharges_list,name='exportcharges_list'),
    path('edit_exportcharges/<int:id>/',views.edit_exportcharges,name='edit_exportcharges'),
    path('delete_exportcharges/<int:id>/',views.delete_exportcharges,name='delete_exportcharges'),

    path('payment/<int:pid>/',views.payment,name='payment'),
    path('complaint/<int:eid>/',views.register_complaint,name='complaint'),
    path('complaint_list',views.complaint_list,name='complaint_list'),
    path('edit_complaint/<int:id>/',views.edit_complaint,name='edit_complaint'),
    path('complaint_complist/<int:id>/',views.complaint_complist,name='complaint_complist'),
    path('reply/<int:id>/',views.reply,name='reply'),
    
    path('register_tender',views.register_tender,name='register_tender'),
    path('tender_list',views.tender_list,name='tender_list'),
    path('edit_tender/<int:id>/',views.edit_tender,name='edit_tender'),
    path('delete_tender/<int:id>/',views.delete_tender,name='delete_tender'),
    path('contractor_tender_list',views.contractor_tender_list,name='contractor_tender_list'),
    path('apply_tender/<int:tid>/',views.apply_tender,name='apply_tender'),
    path('admin_applied_tender_list/<int:id>/',views.admin_applied_tender_list,name='admin_applied_tender_list'),
    
    path('apply_tender_list',views.apply_tender_list,name='apply_tender_list'),
    path('edit_apply_tender/<int:id>/',views.edit_apply_tender,name='edit_apply_tender'),
    path('delete_apply_tender/<int:id>/',views.delete_apply_tender,name='delete_apply_tender'),
    path('tender_approve/<int:id>/',views.tender_approve,name='tender_approve'),
    path('tender_reject/<int:id>/',views.tender_reject,name='tender_reject'),
    
    path('register_temp_job',views.register_temp_job,name='register_temp_job'),
    path('temp_job_list',views.temp_job_list,name='temp_job_list'),
    path('edit_temp_job/<int:id>/',views.edit_temp_job,name='edit_temp_job'),
    path('delete_temp_job/<int:id>/',views.delete_temp_job,name='delete_temp_job'),
    
    path('user_temp_job_list',views.user_temp_job_list,name='user_temp_job_list'),
    path('temp_job_apply/<int:jid>/',views.temp_job_apply,name='temp_job_apply'),
    path('user_applied_job_list',views.user_applied_job_list,name='user_applied_job_list'),
    path('edit_user_applied_job/<int:id>/',views.edit_user_applied_job,name='edit_user_applied_job'),
    path('delete_user_applied_job/<int:id>/',views.delete_user_applied_job,name='delete_user_applied_job'),
    
    path('admin_applied_job_list/<int:id>/',views.admin_applied_job_list,name='admin_applied_job_list'),
    path('temp_job_approve/<int:id>/<int:jid>/',views.temp_job_approve,name='temp_job_approve'),
    path('temp_job_reject/<int:id>/<int:jid>/',views.temp_job_reject,name='temp_job_reject'),
    
    path('register_interview/<int:id>/',views.register_interview,name='register_interview'),
    path('interview_list/<int:id>/',views.interview_list,name='interview_list'),
    path('edit_interview/<int:id>/<int:lid>',views.edit_interview,name='edit_interview'),
    path('delete_interview/<int:id>/<int:lid>',views.delete_interview,name='delete_interview'),
    path('interview_user/<int:id>/',views.interview_user,name='interview_user'),
    
    path('logout',views.logout,name='logout'),
    
    path('company_complaint',views.company_complaint,name='company_complaint'),
    path('company_complaint_list',views.company_complaint_list,name='company_complaint_list'),
    path('edit_company_complaint/<int:id>/',views.edit_company_complaint,name='edit_company_complaint'),
    path('delete_company_complaint/<int:id>/',views.delete_company_complaint,name='delete_company_complaint'),

    path('user_complaint',views.user_complaint,name='user_complaint'),
    path('user_complaint_list',views.user_complaint_list,name='user_complaint_list'),
    path('edit_user_complaint/<int:id>/',views.edit_user_complaint,name='edit_user_complaint'),
    path('delete_user_complaint/<int:id>/',views.delete_user_complaint,name='delete_user_complaint'),

    path('contractor_complaint',views.contractor_complaint,name='contractor_complaint'),
    path('contractor_complaint_list',views.contractor_complaint_list,name='contractor_complaint_list'),
    path('edit_contractor_complaint/<int:id>/',views.edit_contractor_complaint,name='edit_contractor_complaint'),
    path('delete_contractor_complaint/<int:id>/',views.delete_contractor_complaint,name='delete_contractor_complaint'),

    path('admin_all_complaint_list',views.admin_all_complaint_list,name='admin_all_complaint_list'),
    path('admin_reply/<int:id>/',views.admin_reply,name='admin_reply'),
    # added by me
    path('subheader',views.subhead,name='subheader'),
    path('loginnew',views.loginnew,name='login'),
    # path('delete/<int:id>/',views.delete,name='delete'),
    path('dash',views.admin_dash,name='dash'),
    path('admin_head',views.admin_head,name='admin_head'),
    path('user_subheader',views.user_subhead,name='user_subheader'),
    path('company_subheader',views.company_subhead,name='company_subheader'),
    path('contractor_subheader',views.contractor_subhead,name='contractor_subheader'),
    # path('interview_details',views.interview_details, name='interview_details'),

    path('interview_conducting/<int:id>',views.interview_conducting, name='interview_conducting'),
    path('save_video_url/', views.save_video_url, name='save_video_url'),


]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

vizhinjamport/models.py
from django.db import models

# Create your models here.


class Login(models.Model): 
    email=models.EmailField(unique=True)
    password = models.CharField(max_length=100)
    usertype = models.CharField(max_length=100)
    status = models.IntegerField(default=0)
    


class User(models.Model):
    name = models.CharField(max_length=100)
    contact = models.IntegerField()
    district = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    login_id =models.ForeignKey(Login,on_delete=models.CASCADE)

class Company(models.Model):
    company_name = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    reg_no = models.CharField(max_length=100)
    contact = models.IntegerField()
    login_id =models.ForeignKey(Login,on_delete=models.CASCADE)

class Contractor(models.Model):
    name = models.CharField(max_length=100)
    gender = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    dob = models.DateField()
    district = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    reg_no = models.CharField(max_length=100)
    contact = models.IntegerField()
    login_id =models.ForeignKey(Login,on_delete=models.CASCADE)

class Ship(models.Model):
    shipcategory = models.CharField(max_length=100)
    shipname = models.CharField(max_length=100)
    source = models.CharField(max_length=100)
    destination = models.CharField(max_length=100)
    currentdate = models.DateField(auto_now_add=True)
    company_id =models.ForeignKey(Company,on_delete=models.CASCADE)
     
class Export(models.Model):
    productcategory = models.CharField(max_length=100)
    productname = models.CharField(max_length=100)
    quantity = models.IntegerField()
    recipientname = models.CharField(max_length=100)
    recipientaddress = models.CharField(max_length=100)
    recipientcontact = models.IntegerField()
    recipientemail = models.CharField(max_length=100)
    source = models.CharField(max_length=100)
    destination = models.CharField(max_length=100)
    publicid = models.ForeignKey(User,on_delete=models.CASCADE)
    shipid = models.ForeignKey(Ship,on_delete=models.CASCADE)
    currentdate = models.DateField(auto_now_add=True)
    paymentstatus = models.IntegerField(default=0) 
    cancelstatus = models.IntegerField(default=0)
    refundstatus = models.IntegerField(default=0)
    exportstatus = models.IntegerField(default=0) 
    def __str__(self):
        return f"{self.productcategory} - {self.productname} ({self.quantity})"

class ExportCharges(models.Model):
    company_id = models.ForeignKey(Company,on_delete=models.CASCADE)
    productcategory = models.CharField(max_length=100)
    productname = models.CharField(max_length=100)
    amount = models.IntegerField()
    tax = models.IntegerField()
    currentdate = models.DateField(auto_now_add=True)

class Payment(models.Model):
    cardholder=models.CharField(max_length=100)
    cardno=models.IntegerField()
    cvv=models.IntegerField()
    expirydate=models.IntegerField()
    expiryyear=models.IntegerField()
    amount=models.IntegerField()
    login_id =models.ForeignKey(Login,on_delete=models.CASCADE)
    currentdate = models.DateField(auto_now_add=True)

class Complaint(models.Model):
    subject=models.CharField(max_length=100)
    complaint=models.TextField(max_length=200)
    image=models.FileField(upload_to='complaints/')
    reply=models.TextField(null=True)
    export_id=models.ForeignKey(Export,on_delete=models.CASCADE)
    user_id=models.ForeignKey(User,on_delete=models.CASCADE)
    currentdate = models.DateField(auto_now_add=True)

class Tender(models.Model):
    category=models.CharField(max_length=100)
    name=models.CharField(max_length=100)
    discription=models.TextField(max_length=200)
    amount=models.IntegerField()
    no_of_month=models.IntegerField()
    last_date_apply=models.DateField()
    currentdate = models.DateField(auto_now_add=True)

class AppliedTender(models.Model):
    tender_id=models.ForeignKey(Tender,on_delete=models.CASCADE)
    contractor_id=models.ForeignKey(Contractor,on_delete=models.CASCADE)
    amount=models.IntegerField()
    currentdate = models.DateField(auto_now_add=True)
    applystatus = models.IntegerField(default=0)

class TempJob(models.Model):
    name=models.CharField(max_length=100)
    category=models.CharField(max_length=100)
    discription=models.TextField(max_length=247)
    lastdateapply=models.DateField()
    currentdate = models.DateField(auto_now_add=True)
    url = models.URLField(null=True)

class ApplyJob(models.Model):
    job_id=models.ForeignKey(TempJob,on_delete=models.CASCADE)
    user_id=models.ForeignKey(User,on_delete=models.CASCADE)
    qualification=models.CharField(max_length=100)
    documents=models.FileField(upload_to='documents/')
    currentdate = models.DateField(auto_now_add=True)
    status = models.IntegerField(default=0)

class Interview(models.Model):
    job_id=models.ForeignKey(TempJob,on_delete=models.CASCADE)
    time=models.TimeField()
    date=models.DateField()
    venue=models.CharField(max_length=100)
    discription=models.TextField(max_length=247)
    currentdate = models.DateField(auto_now_add=True)    

class News(models.Model):
    news=models.TextField()
    currentdate = models.DateField(auto_now_add=True)

class ShipTracking(models.Model):
    currentlocation=models.CharField(max_length=100)
    time=models.TimeField()
    date=models.DateField()
    ship_id=models.ForeignKey(Ship,on_delete=models.CASCADE)
    ship_status=models.IntegerField(default=0)

class AllComplaint(models.Model):
    login_id=models.ForeignKey(Login,on_delete=models.CASCADE)
    complaint=models.TextField()
    reply=models.TextField()
    currentdate=models.DateField(auto_now_add=True)
    

vizhinjamport/templates/admin_edit_news.html
{% extends 'admin_header.html' %}
  {% block content %}
    <!-- <h2>News (edit)</h2> -->
    {% if messages %}
         {% for message in messages %}
            <p style="color:green;">{{ message }}</p>
          {% endfor %}
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary btn-style">register</button>

    </form>       
  {% endblock %}

vizhinjamport/templates/company_complaint_edit.html
{% extends 'company_subheader.html' %}
{% block content %}

<div class="container my-5">
    <div class="card shadow-lg border-0 rounded-4">
        
        <!-- Header -->
        <div class="card-header text-white" style="background-color: #ff9800;">
            <h4 class="mb-0"><i class="fas fa-comment-dots me-2"></i> Company Complaint</h4>
        </div>

        <div class="card-body">
            <!-- Messages -->
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <i class="fas fa-check-circle me-2"></i> {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}

            <!-- Complaint Form -->
            <form method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    {{ form.subject.label_tag }}
                    {{ form.subject }}
                </div>
                <div class="mb-3">
                    {{ form.complaint.label_tag }}
                    {{ form.complaint }}
                </div>

                <div class="text-center mt-4">
                    <button type="submit" class="btn btn-primary btn-lg px-5">
                        <i class="fas fa-paper-plane me-2"></i> Register Complaint
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

vizhinjamport/templates/complaint.html
{% extends 'user_subheader.html' %}
{% block content %}

<div class="container my-5">
    <div class="card shadow-lg border-0 rounded-4">
        
        <!-- Header -->
        <div class="card-header text-white" style="background-color: #ff9800;">
            <h4 class="mb-0"><i class="fas fa-comment-dots me-2"></i>Export Complaint Registration</h4>
        </div>

        <div class="card-body">
            <!-- Messages -->
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <i class="fas fa-check-circle me-2"></i> {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}

            <!-- Complaint Form -->
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    {{ form.subject.label_tag }}
                    {{ form.subject }}
                </div>
                <div class="mb-3">
                    {{ form.complaint.label_tag }}
                    {{ form.complaint }}
                </div>
                <div class="mb-3">
                    {{ form.image.label_tag }}
                    {{ form.image }}
                </div>

                <div class="text-center mt-4">
                    <button type="submit" class="btn btn-lg px-5 text-white" style="background-color: #ff9800;">
                        <i class="fas fa-paper-plane me-2"></i> Submit Complaint
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

vizhinjamport/templates/export_comp_list.html
{% extends 'company_subheader.html' %}
{% block content %}

<div class="container mt-4">
    <div class="card shadow-lg rounded-3">
        <div class="card-header text-white" style="background-color:  #ff9800;">
            <h4 class="mb-0">Export List</h4>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-hover text-center align-middle">
                    <thead class="table-dark">
                        <tr>
                            <th>User Name</th>
                            <th>Email</th>
                            <th>Product Category</th>
                            <th>Product Name</th>
                            <th>Quantity</th>
                            <th>Recipient Name</th>
                            <th>Recipient Address</th>
                            <th>Recipient Contact</th>
                            <th>Recipient Email</th>
                            <th>Source</th>
                            <th>Destination</th>
                            <th>Ship Name</th>
                            <th>Complaints</th>
                            <th>Refund</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for data in exports %}
                        <tr>
                            <td>{{ data.publicid.name }}</td>
                            <td>{{ data.publicid.login_id.email }}</td>
                            <td>{{ data.productcategory }}</td>
                            <td>{{ data.productname }}</td>
                            <td>{{ data.quantity }}</td>
                            <td>{{ data.recipientname }}</td>
                            <td>{{ data.recipientaddress }}</td>
                            <td>{{ data.recipientcontact }}</td>
                            <td>{{ data.recipientemail }}</td>
                            <td>{{ data.source }}</td>
                            <td>{{ data.destination }}</td>
                            <td>{{ data.shipid.shipname }}</td>
                            <td>
                                <a href="{% url 'complaint_complist' data.id %}" class="btn btn-sm btn-warning">
                                    View
                                </a>
                            </td>
                            <td>
    {% if data.complaint_set.exists %}
        {% if data.refundstatus == 0 %}
            <a href="{% url 'refund_export' data.id %}" class="btn btn-sm btn-danger">
                Refund
            </a>
        {% else %}
            <span class="badge bg-success">Refunded</span>
        {% endif %}
    {% else %}
        <span class="text-muted">No complaints</span>
    {% endif %}
</td>

                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="14" class="text-muted">No export records found.</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

vizhinjamport/templates/exportcharge_edit.html
{% extends 'company_subheader.html' %}
{% block content %}

<div class="container mt-4">
    <div class="card shadow-lg rounded-3">
        <div class="card-header text-white" style="background-color: #ff9800;">
            <h4 class="mb-0">Add Export Chrages</h4>
        </div>
        <div class="card-body">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success">{{ message }}</div>
                {% endfor %}
            {% endif %}

            <form method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>

<!-- jQuery (make sure it's loaded only once) -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(function(){  // DOM ready

    const productChoices = {
        'Electronics': [
            {value: 'Laptop&parts', text: 'Laptop & Parts'},
            {value: 'electronic gadgets', text: 'Electronic Gadgets'},
            {value: 'mobile phones', text: 'Mobile Phones'},
            {value: 'television', text: 'Television'}
        ],
        'Furniture': [
            {value: 'Chair', text: 'Chair'},
            {value: 'Table', text: 'Table'},
            {value: 'sofa', text: 'Sofa'},
            {value: 'bed', text: 'Bed'}
        ]
    };

    function populateProducts(category, selectedValue = '') {
        var productSelect = $("#id_productname");
        productSelect.empty();
        productSelect.append($('<option>', { value: '', text: '--- Select Product ---' }));
        if (category && productChoices[category]) {
            productChoices[category].forEach(function (item) {
                productSelect.append($('<option>', {
                    value: item.value,
                    text: item.text
                }));
            });
            if (selectedValue) {
                productSelect.val(selectedValue);
            }
        }
    }

    // On change populate list
    $("#id_productcategory").on('change', function () {
        populateProducts($(this).val());
    });

    // On page load (for validation error case)
    const initialCategory = $("#id_productcategory").val();
    const initialProduct = $("#id_productname").val();
    if (initialCategory) {
        populateProducts(initialCategory, initialProduct);
    }
});
</script>

{% endblock %}

vizhinjamport/templates/interview_reg.html
{% extends 'admin_header.html' %}
  {% block content %}
    <!-- <h2>interview</h2> -->
    {% if messages %}
         {% for message in messages %}
                <p style="color:green;">{{ message }}</p>
          {% endfor %}
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary btn-style">register</button>

    </form>       
  {% endblock %}

vizhinjamport/templates/login.html
    <h2>Login</h2>
    {% if msg %}
                <p style="color:rgb(114, 0, 0);">{{ msg }}</p>
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        <input type="email" placeholder="example" name="email">
        <br>
        <input type="password" placeholder="password" name="password">
        <br>
        
        <button type="submit">Login</button>

    </form>       

vizhinjamport/templates/news_list.html
{% extends 'subheader.html' %}
{% block content %}

<div class="container my-5">
    <h2 class="text-center mb-4 fw-bold" style="color:#ff9800;">
        <i class="fas fa-newspaper me-2"></i> Latest News
    </h2>

    <div class="row">
        {% for new in news %}
        <div class="col-md-4 mb-4">
            <div class="card h-100 shadow-lg border-0 news-card">
                
                <!-- Card Body -->
                <div class="card-body">
                    <h5 class="card-title fw-bold">
                        <i class="fas fa-bullhorn me-2" style="color:#ff9800;"></i> <span style="color:#ff9800;">News</span>
                    </h5>
                    <p class="card-text">{{ new.news }}</p>
                </div>
                
                <!-- Card Footer -->
                <div class="card-footer bg-white text-muted d-flex justify-content-between align-items-center">
                    <span class="badge bg-warning text-dark">
                        <i class="fas fa-calendar-alt me-1"></i> {{ new.currentdate }}
                    </span>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="col-12 text-center">
            <p class="text-muted">No news available at the moment.</p>
        </div>
        {% endfor %}
    </div>
</div>

<!-- Extra CSS for hover effects -->
<style>
    .news-card {
        transition: transform 0.2s ease, box-shadow 0.2s ease;
    }
    .news-card:hover {
        transform: translateY(-5px);
        box-shadow: 0px 6px 20px rgba(0, 0, 0, 0.15);
        border-left: 4px solid #ff9800;
    }
</style>

{% endblock %}

vizhinjamport/templates/ship_list.html
{% extends 'company_subheader.html' %}
{% block content %}

<div class="container mt-4">
    <h3 class="mb-3 text-center" style="color: #ff9800;">Ship List</h3>

    <table class="table table-striped table-hover table-bordered shadow-sm">
        <thead class="table-dark text-center">
            <tr>
                <th>Ship Category</th>
                <th>Ship Name</th>
                <th>Source</th>
                <th>Destination</th>
                <th>Current Date</th>
                <th colspan="2">Options</th>
                <th colspan="2">Tracking</th>
            </tr>
        </thead>
        <tbody>
            {% for ship in ships %}
            <tr>
                <td>{{ ship.shipcategory }}</td>
                <td>{{ ship.shipname }}</td>
                <td>{{ ship.source }}</td>
                <td>{{ ship.destination }}</td>
                <td>{{ ship.currentdate }}</td>
                <td>
                    <a href="{% url 'edit_ship' ship.id %}" class="btn btn-sm btn-warning">Edit</a>
                </td>
                <td>
                    <a href="{% url 'delete_ship' ship.id %}" class="btn btn-sm btn-danger">Delete</a>
                </td>
                <td>
                    <a href="{% url 'ship_track' ship.id %}" class="btn btn-sm btn-primary">Update</a>
                </td>
                <td>
                    <a href="{% url 'ship_track_list' ship.id %}" class="btn btn-sm btn-success">View Locations</a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="9" class="text-center text-muted">No ships found.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

vizhinjamport/templates/temp_job_apply.html
{% extends 'user_subheader.html' %}
{% block content %}

<div class="container mt-4">
    <h3 class="mb-3 text-center" style="background-color: #ff9800;">Temporary Job Application</h3>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success">{{ message }}</div>
        {% endfor %}
    {% endif %}

    <form method="POST" enctype="multipart/form-data" class="p-4 border rounded shadow-sm bg-light">
        {% csrf_token %}
        
        {% for field in form %}
            <div class="mb-3">
                <label class="form-label">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                    <div class="text-danger small">{{ field.errors }}</div>
                {% endif %}
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-success w-100">Apply</button>
    </form>
</div>

{% endblock %}

vizhinjamport/templates/tender_reg.html
{% extends 'admin_header.html' %}
  {% block content %}
    <!-- <h2>Tender Registeration</h2> -->
    {% if messages %}
         {% for message in messages %}
                <p style="color:green;">{{ message }}</p>
          {% endfor %}
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary btn-style">register</button>

    </form>       
  {% endblock %}

vizhinjamport/templates/user_applied_job_edit.html
{% extends 'user_subheader.html' %}
{% block content %}

<div class="container mt-4">
    <h3 class="mb-3 text-center" style="color: #ff9800;">Temporary Job Application</h3>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success">{{ message }}</div>
        {% endfor %}
    {% endif %}

    <form method="POST" enctype="multipart/form-data" class="p-4 border rounded shadow-sm bg-light">
        {% csrf_token %}
        
        {% for field in form %}
            <div class="mb-3">
                <label class="form-label">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                    <div class="text-danger small">{{ field.errors }}</div>
                {% endif %}
            </div>
        {% endfor %}

        <button type="submit" class="btn w-100" style="background-color: #ff9800;">Apply</button>
    </form>
</div>

{% endblock %}